In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from scipy.stats import zscore

In [4]:
Fraud_train = pd.read_csv("fraudTrain.csv")
Fraud_test = pd.read_csv("fraudTest.csv")

print("Training Data Shape:", Fraud_train.shape)
print("Testing Data Shape:", Fraud_test.shape)

Training Data Shape: (1296675, 23)
Testing Data Shape: (555719, 23)

In [5]:
Fraud_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [6]:
Fraud_test.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [8]:
Fraud_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [9]:
Fraud_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

In [10]:
Fraud_train.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,6.483370e+05,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [11]:
Fraud_test.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,555719.000000,5.557190e+05,555719.000000,555719.000000,555719.000000,555719.000000,5.557190e+05,5.557190e+05,555719.000000,555719.000000,555719.000000
mean,277859.000000,4.178387e+17,69.392810,48842.628015,38.543253,-90.231325,8.822189e+04,1.380679e+09,38.542798,-90.231380,0.003860
std,160422.401459,1.309837e+18,156.745941,26855.283328,5.061336,13.721780,3.003909e+05,5.201104e+06,5.095829,13.733071,0.062008
min,0.000000,6.041621e+10,1.000000,1257.000000,20.027100,-165.672300,2.300000e+01,1.371817e+09,19.027422,-166.671575,0.000000
25%,138929.500000,1.800429e+14,9.630000,26292.000000,34.668900,-96.798000,7.410000e+02,1.376029e+09,34.755302,-96.905129,0.000000
50%,277859.000000,3.521417e+15,47.290000,48174.000000,39.371600,-87.476900,2.408000e+03,1.380762e+09,39.376593,-87.445204,0.000000
75%,416788.500000,4.635331e+15,83.010000,72011.000000,41.894800,-80.175200,1.968500e+04,1.385867e+09,41.954163,-80.264637,0.000000
max,555718.000000,4.992346e+18,22768.110000,99921.000000,65.689900,-67.950300,2.906700e+06,1.388534e+09,66.679297,-66.952026,1.000000

In [12]:
print("Missing values in Training Data:")
print(Fraud_train.isnull().sum())

Missing values in Training Data:
Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [13]:
print("Missing values in Testing Data:")
print(Fraud_test.isnull().sum())

Missing values in Testing Data:
Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [14]:
print("Training Data:")
print(Fraud_train['is_fraud'].value_counts())

print("\nTesting Data:")
print(Fraud_test['is_fraud'].value_counts())

Training Data:
is_fraud
0    1289169
1       7506
Name: count, dtype: int64

Testing Data:
is_fraud
0    553574
1      2145
Name: count, dtype: int64

In [15]:
print("Training Fraud Percentage:")
print(Fraud_train['is_fraud'].value_counts(normalize=True) * 100)

print("\nTesting Fraud Percentage:")
print(Fraud_test['is_fraud'].value_counts(normalize=True) * 100)

Training Fraud Percentage:
is_fraud
0    99.421135
1     0.578865
Name: proportion, dtype: float64

Testing Fraud Percentage:
is_fraud
0    99.614014
1     0.385986
Name: proportion, dtype: float64

In [16]:
bins = [0, 50, 100, 500, 1000, np.inf]

bin_names = [
    'Low',
    'Medium',
    'High',
    'Very High',
    'Extreme'
]

Fraud_train['amt_bin'] = pd.cut(
    Fraud_train['amt'],
    bins=bins,
    labels=bin_names
)

Fraud_train[['amt', 'amt_bin']].head(10)

      amt amt_bin
0    4.97     Low
1  107.23    High
2  220.11    High
3   45.00     Low
4   41.96     Low
5   94.63  Medium
6   44.54     Low
7   71.65  Medium
8    4.27     Low
9  198.39    High

In [17]:
pd.value_counts(Fraud_train['amt_bin'])

C:\Users\prach\AppData\Local\Temp\ipykernel_24672\2515279974.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(Fraud_train['amt_bin'])

amt_bin
Low          672299
Medium       389483
High         219262
Very High     11695
Extreme        3936
Name: count, dtype: int64

In [18]:
Fraud_test['amt_bin'] = pd.cut(
    Fraud_test['amt'],
    bins=bins,
    labels=bin_names
)

Fraud_test[['amt', 'amt_bin']].head(10)

      amt amt_bin
0    2.86     Low
1   29.84     Low
2   41.28     Low
3   60.05  Medium
4    3.19     Low
5   19.55     Low
6  133.93    High
7   10.37     Low
8    4.37     Low
9   66.54  Medium

In [19]:
Fraud_train['amt_quantile_bin'] = pd.qcut(
    Fraud_train['amt'],
    4,
    labels=['Q1', 'Q2', 'Q3', 'Q4']
)

Fraud_train[['amt', 'amt_quantile_bin']].head(10)

      amt amt_quantile_bin
0    4.97               Q1
1  107.23               Q4
2  220.11               Q4
3   45.00               Q2
4   41.96               Q2
5   94.63               Q4
6   44.54               Q2
7   71.65               Q3
8    4.27               Q1
9  198.39               Q4

In [20]:
pd.value_counts(Fraud_train['amt_quantile_bin'])

C:\Users\prach\AppData\Local\Temp\ipykernel_24672\951074547.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(Fraud_train['amt_quantile_bin'])

amt_quantile_bin
Q1    324325
Q3    324151
Q4    324112
Q2    324087
Name: count, dtype: int64

In [21]:
numeric_features = [
    'amt',
    'lat',
    'long',
    'city_pop',
    'merch_lat',
    'merch_long'
]

train_numeric = Fraud_train[numeric_features]
test_numeric = Fraud_test[numeric_features]

In [22]:
min_max_scaler = MinMaxScaler()

Fraud_train_min_max = pd.DataFrame(
    min_max_scaler.fit_transform(train_numeric),
    columns=numeric_features
)

Fraud_train_min_max.head()

        amt       lat      long  city_pop  merch_lat  merch_long
0  0.000137  0.343968  0.864638  0.001194   0.350302    0.848602
1  0.003670  0.618450  0.485682  0.000043   0.621488    0.486208
2  0.007569  0.474727  0.546553  0.001421   0.497559    0.546697
3  0.001520  0.561509  0.548070  0.000659   0.577663    0.542619
4  0.001415  0.394153  0.882190  0.000026   0.405244    0.882857

In [23]:
Fraud_test_min_max = pd.DataFrame(
    min_max_scaler.transform(test_numeric),
    columns=numeric_features
)

Fraud_test_min_max.head()

        amt       lat      long  city_pop  merch_lat  merch_long
0  0.000064  0.298692  0.867121  0.114727   0.308536    0.857102
1  0.000996  0.434867  0.565239  0.000096   0.421239    0.568699
2  0.001391  0.442414  0.942836  0.011860   0.442800    0.927345
3  0.002040  0.183058  0.868312  0.018834   0.201817    0.860288
4  0.000076  0.519129  0.825355  0.000379   0.534860    0.810131

In [24]:
standard_scaler = StandardScaler()

Fraud_train_standard = pd.DataFrame(
    standard_scaler.fit_transform(train_numeric),
    columns=numeric_features
)

Fraud_train_standard.head()

        amt       lat      long  city_pop  merch_lat  merch_long
0 -0.407826 -0.484420  0.657620 -0.282589  -0.494354    0.593864
1  0.230039  2.039120 -2.033870 -0.293670   2.078699   -2.030341
2  0.934149  0.717754 -1.601537 -0.280406   0.902849   -1.592323
3 -0.158132  1.515617 -1.590766 -0.287742   1.662886   -1.621848
4 -0.177094 -0.023035  0.782279 -0.293835   0.026941    0.841909

In [25]:
Fraud_test_standard = pd.DataFrame(
    standard_scaler.transform(test_numeric),
    columns=numeric_features
)

Fraud_test_standard.head()

        amt       lat      long  city_pop  merch_lat  merch_long
0 -0.420988 -0.900689  0.675252  0.810291  -0.890634    0.655413
1 -0.252695  0.351290 -1.468825 -0.293163   0.178708   -1.433000
2 -0.181336  0.420678  1.213006 -0.179922   0.383279    1.164059
3 -0.064255 -1.963810  0.683711 -0.112789  -1.903199    0.678480
4 -0.418929  1.125984  0.378611 -0.290434   1.256767    0.315279

In [26]:
robust_scaler = RobustScaler()

Fraud_train_robust = pd.DataFrame(
    robust_scaler.fit_transform(train_numeric),
    columns=numeric_features
)

Fraud_train_robust.head()

        amt       lat      long  city_pop  merch_lat  merch_long
0 -0.578990 -0.447479  0.378534  0.053051  -0.464366    0.323525
1  0.812491  1.302409 -1.846971 -0.117794   1.355748   -1.845569
2  2.348483  0.386139 -1.489489  0.086699   0.523981   -1.483516
3 -0.034290  0.939398 -1.480583 -0.026398   1.061612   -1.507921
4 -0.075657 -0.127543  0.481611 -0.120347  -0.095615    0.528552

In [27]:
Fraud_test_robust = pd.DataFrame(
    robust_scaler.transform(test_numeric),
    columns=numeric_features
)

Fraud_test_robust.head()

        amt       lat      long   city_pop  merch_lat  merch_long
0 -0.607702 -0.736130  0.393113  16.902783  -0.744683    0.374400
1 -0.240577  0.132024 -1.379754  -0.109982   0.011742   -1.351824
2 -0.084910  0.180139  0.837764   1.635946   0.156450    0.794832
3  0.170499 -1.473326  0.400108   2.670973  -1.460947    0.393466
4 -0.603211  0.669217  0.147831  -0.067909   0.774333    0.093254

In [28]:
Fraud_train['amt_zscore'] = zscore(Fraud_train['amt'])

Fraud_train[['amt', 'amt_zscore']].head(10)

      amt  amt_zscore
0    4.97   -0.407826
1  107.23    0.230039
2  220.11    0.934149
3   45.00   -0.158132
4   41.96   -0.177094
5   94.63    0.151444
6   44.54   -0.161001
7   71.65    0.008103
8    4.27   -0.412192
9  198.39    0.798666

In [29]:
zscore_outliers = Fraud_train[
    np.abs(Fraud_train['amt_zscore']) > 3
]

zscore_outliers.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,amt_bin,amt_quantile_bin,amt_zscore
138,138,2019-01-01 01:41:22,4060579726528237,"fraud_Baumbach, Hodkiewicz and Walsh",shopping_pos,636.41,Steven,Sanders,M,25955 Amy Via,...,Theatre director,1948-11-14,25240538cb76fe0e9f55c3eb2c5e3bf9,1325382082,39.936995,-94.604311,0,Very High,Q4,3.530896
232,232,2019-01-01 02:54:10,4311368326621416041,fraud_Kassulke PLC,shopping_net,1055.47,Phillip,Delacruz,M,26678 Lisa Locks Apt. 904,...,Community arts worker,1969-09-21,adca67d0a40b26fb8afeccbae31b7828,1325386450,39.940564,-103.528231,0,Extreme,Q4,6.144858
296,296,2019-01-01 03:51:28,571844099986,fraud_Heathcote LLC,shopping_net,909.66,Susan,Mills,F,005 Cody Estates,...,Engineering geologist,1952-04-02,ecea96ae40920997dd56b4e0b408d623,1325389888,39.081318,-86.301580,0,Very High,Q4,5.235342
511,511,2019-01-01 06:43:54,4509142395811241,fraud_McGlynn-Heathcote,misc_net,1636.87,Margaret,Williams,F,165 Jerry Meadows Suite 460,...,"Engineer, technical sales",1926-07-12,9b13fb1ce565b55afe4106ecdee9346b,1325400234,31.608415,-83.145823,0,Extreme,Q4,9.771446
723,723,2019-01-01 09:23:55,4265776278887457,"fraud_Rippin, Kub and Mann",misc_net,1047.52,Christine,Best,F,68248 Deanna Land,...,"Physicist, medical",1954-01-05,bb5654f0f82ace48aa6e4f45db7c64c5,1325409835,34.887449,-92.623326,0,Extreme,Q4,6.095269

In [30]:
print("Number of outliers:", zscore_outliers.shape[0])

Number of outliers: 12738

In [31]:
zscore_outliers['is_fraud'].value_counts()

is_fraud
0    9141
1    3597
Name: count, dtype: int64

In [32]:
fraud_percentage = zscore_outliers['is_fraud'].mean() * 100

print("Fraud percentage among detected outliers:",
      fraud_percentage, "%")

Fraud percentage among detected outliers: 28.238341968911918 %

In [33]:
Q1 = Fraud_train['amt'].quantile(0.25)
Q3 = Fraud_train['amt'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 9.65
Q3: 83.14
IQR: 73.49
Lower Bound: -100.58499999999998
Upper Bound: 193.375

In [34]:
iqr_outliers = Fraud_train[
    (Fraud_train['amt'] < lower_bound) |
    (Fraud_train['amt'] > upper_bound)
]

iqr_outliers.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,amt_bin,amt_quantile_bin,amt_zscore
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,High,Q4,0.934149
9,9,2019-01-01 00:06:01,2720830304681674,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,21326 Taylor Squares Suite 708,...,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1325376361,37.179198,-87.485381,0,High,Q4,0.798666
16,16,2019-01-01 00:10:49,6011860238257910,fraud_Lebsack and Sons,misc_net,327.00,Lisa,Mendez,F,44259 Beth Station Suite 215,...,"Programme researcher, broadcasting/film/video",1952-07-06,991c04803b4d4eeab30d6245a872e3d3,1325376649,36.384092,-99.048472,0,High,Q4,1.600894
17,17,2019-01-01 00:10:58,3565423334076143,fraud_Mayert Group,shopping_pos,341.67,Nathan,Thomas,M,4923 Campbell Pines Suite 717,...,Energy engineer,1938-03-15,f12cf52be2175703db789a4644c32f25,1325376658,38.674491,-88.305767,0,High,Q4,1.692401
36,36,2019-01-01 00:26:22,3598215285024754,fraud_Heidenreich PLC,grocery_pos,207.36,Ashley,Lopez,F,9333 Valentine Point,...,"Librarian, public",1970-10-21,f246ac27c09429ff1e385d4683c79c4d,1325377582,40.202538,-73.859212,0,High,Q4,0.854618

In [35]:
print("Number of IQR outliers:", iqr_outliers.shape[0])

Number of IQR outliers: 67290

In [36]:
iqr_outliers['is_fraud'].value_counts()

is_fraud
0    61585
1     5705
Name: count, dtype: int64

In [37]:
fraud_percentage_iqr = iqr_outliers['is_fraud'].mean() * 100

print("Fraud percentage among IQR outliers:",
      fraud_percentage_iqr, "%")

Fraud percentage among IQR outliers: 8.478228562936543 %

In [38]:
test_iqr_outliers = Fraud_test[
    (Fraud_test['amt'] < lower_bound) |
    (Fraud_test['amt'] > upper_bound)
]

test_iqr_outliers.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,amt_bin
33,33,2020-06-21 12:26:23,180036456789979,fraud_Nienow PLC,entertainment,210.36,Mackenzie,Salazar,F,982 Melissa Lock,...,-91.0685,878,Risk analyst,1974-11-20,902facfd912019350d63a3539990638e,1371817583,42.736666,-90.099710,0,High
100,100,2020-06-21 12:45:48,6592074504369261,fraud_Greenholt Ltd,health_fitness,242.35,Amanda,Molina,F,8425 Daniel Knolls Suite 288,...,-74.9781,1526206,Commercial horticulturist,1972-05-23,39db7261e2dd32311c1e5ff2a52bac79,1371818748,39.151823,-75.035003,0,High
133,133,2020-06-21 12:55:19,4683638447911,fraud_Gislason Group,travel,558.03,Daniel,Boyd,M,8925 Nicholas Points,...,-92.5002,1261,Broadcast presenter,1972-07-01,95427dcec71aa88ad39bf523084d1bca,1371819319,30.870870,-92.873036,0,Very High
167,167,2020-06-21 13:08:46,6011109736646996,fraud_Schumm PLC,shopping_net,1199.45,Rebecca,Erickson,F,594 Berry Lights Apt. 392,...,-77.8670,186140,English as a second language teacher,1983-02-08,249ecb7b44d6d42a8eb155833fe23c53,1371820126,34.622777,-77.827863,0,Extreme
245,245,2020-06-21 13:36:21,4476840372112,fraud_Heathcote LLC,shopping_net,236.15,Steven,Walters,M,3206 Hall Divide Suite 282,...,-86.2296,3395,"Editor, commissioning",1979-01-21,d8188cc764b76befb9196b2d137b6e16,1371821781,33.831991,-85.328265,0,High

In [39]:
print("Number of test outliers:", test_iqr_outliers.shape[0])

Number of test outliers: 27673

In [40]:
print("Actual labels of detected test outliers:")
print(test_iqr_outliers['is_fraud'].value_counts())

Actual labels of detected test outliers:
is_fraud
0    26060
1     1613
Name: count, dtype: int64

In [41]:
test_fraud_percentage = (
    test_iqr_outliers['is_fraud'].mean() * 100
)

print(
    "Percentage of detected test outliers that are fraudulent:",
    test_fraud_percentage,
    "%"
)

Percentage of detected test outliers that are fraudulent: 5.828786181476529 %

In [42]:
comparison = pd.DataFrame({
    'Actual Fraud': [
        Fraud_test['is_fraud'].sum(),
        Fraud_test['is_fraud'].value_counts().get(0, 0)
    ],
    'Detected IQR Outliers': [
        test_iqr_outliers['is_fraud'].sum(),
        (test_iqr_outliers['is_fraud'] == 0).sum()
    ]
}, index=['Fraud', 'Legitimate'])

comparison

            Actual Fraud  Detected IQR Outliers
Fraud               2145                   1613
Legitimate        553574                  26060

In [43]:
fraudulent_outliers = test_iqr_outliers[
    test_iqr_outliers['is_fraud'] == 1
]

fraudulent_outliers[
    ['trans_date_trans_time', 'cc_num', 'merchant',
     'category', 'amt', 'city', 'state', 'is_fraud']
].head(20)

,trans_date_trans_time,cc_num,merchant,category,amt,city,state,is_fraud
1767,2020-06-21 22:32:22,6564459919350820,"fraud_Rodriguez, Yost and Jenkins",misc_net,780.52,Benton,WI,1
1781,2020-06-21 22:37:27,6564459919350820,fraud_Nienow PLC,entertainment,620.33,Benton,WI,1
1784,2020-06-21 22:38:55,4005676619255478,"fraud_Heathcote, Yost and Kertzmann",shopping_net,1077.69,Denham Springs,LA,1
1857,2020-06-21 23:02:16,3560725013359375,fraud_Hermann and Sons,shopping_pos,842.65,Notrees,TX,1
1906,2020-06-21 23:21:44,4005676619255478,fraud_Kuhic LLC,shopping_net,1128.26,Denham Springs,LA,1
1956,2020-06-21 23:35:27,4005676619255478,"fraud_Reichert, Rowe and Mraz",shopping_net,931.82,Denham Springs,LA,1
1968,2020-06-21 23:40:26,4005676619255478,"fraud_Kihn, Abernathy and Douglas",shopping_net,983.00,Denham Springs,LA,1
2026,2020-06-21 23:59:05,6564459919350820,fraud_Lemke-Gutmann,shopping_net,955.16,Benton,WI,1
2039,2020-06-22 00:06:40,4005676619255478,"fraud_Rodriguez, Yost and Jenkins",misc_net,701.81,Denham Springs,LA,1
2195,2020-06-22 01:25:13,4005676619255478,"fraud_Goldner, Kovacek and Abbott",grocery_pos,326.94,Denham Springs,LA,1
2258,2020-06-22 01:54:33,3524574586339330,"fraud_Osinski, Ledner and Leuschke",grocery_pos,353.08,Vero Beach,FL,1
2467,2020-06-22 03:38:35,4005676619255478,"fraud_Kerluke, Considine and Macejkovic",misc_net,868.48,Denham Springs,LA,1
2506,2020-06-22 03:55:36,3524574586339330,fraud_Kuhn LLC,shopping_pos,777.45,Vero Beach,FL,1
2650,2020-06-22 04:58:25,3524574586339330,fraud_Schumm PLC,shopping_net,967.86,Vero Beach,FL,1
5669,2020-06-22 21:51:05,4005676619255478,"fraud_Baumbach, Strosin and Nicolas",shopping_pos,825.81,Denham Springs,LA,1
6023,2020-06-22 23:35:47,3524574586339330,fraud_Kutch-Wilderman,home,250.32,Vero Beach,FL,1
10036,2020-06-24 00:26:45,180098888332620,fraud_DuBuque LLC,grocery_pos,315.45,Springville,NY,1
10047,2020-06-24 00:44:24,180098888332620,"fraud_Huel, Hammes and Witting",grocery_pos,279.78,Springville,NY,1
10167,2020-06-24 02:56:50,180098888332620,fraud_Murray-Smitham,grocery_pos,287.38,Springville,NY,1
10193,2020-06-24 03:21:56,180098888332620,fraud_Heidenreich PLC,grocery_pos,276.40,Springville,NY,1

In [44]:
print("Total Test Transactions:", len(Fraud_test))
print("Actual Fraud Transactions:", Fraud_test['is_fraud'].sum())
print("Detected Outliers:", len(test_iqr_outliers))
print("Fraudulent Transactions Among Outliers:",
      test_iqr_outliers['is_fraud'].sum())

Total Test Transactions: 555719
Actual Fraud Transactions: 2145
Detected Outliers: 27673
Fraudulent Transactions Among Outliers: 1613